server:
  port: ${PORT:2333}
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0" # Use the latest stable version
      repository: "https://maven.lavalink.dev/releases"
  server:
    password: ${LAVALINK_PASSWORD:youshallnotpass}
    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      http: true
      local: false

logging:
  level:
    root: INFO
    lavalink: INFO
