server:
  port: ${PORT}
  address: 0.0.0.0

lavalink:
  server:
    password: "${LAVALINK_PASSWORD}"
    sources:
      youtube: true
      soundcloud: true
      bandcamp: true
      http: true
      local: false

logging:
  level:
    root: INFO
    lavalink: INFO
